{
 "title": "Docker",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "container_name", "label": "Container", "query": "label_values(container_name)" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(dex_container_running, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Containers running",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dex_container_running{job=~\"$job\"} == 1)"
    }
   ]
  },
  {
   "title": "Containers not running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dex_container_running{job=~\"$job\"} == 0)"
    }
   ]
  },
  {
   "title": "Cpu utilization",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "cpu utilization" }
   ],
   "targets": [
    {
     "expr": "dex_cpu_utilization_percent{job=~\"$job\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "decbytes", "label": "memory usage" }
   ],
   "targets": [
    {
     "expr": "dex_memory_usage_bytes{job=~\"$job\",container_name=~\"$container_name\"}",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(dex_memory_usage_bytes{job=~\"$job\",container_name=~\"$container_name\"})",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Block I/O write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(dex_block_io_write_bytes_total{job=~\"$job\",container_name=~\"$container_name\"}[5m])",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(dex_network_rx_bytes_total{job=~\"$job\",container_name=~\"$container_name\"}[5m])",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Block I/O read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(dex_block_io_read_bytes_total{job=~\"$job\",container_name=~\"$container_name\"}[5m])",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(dex_network_tx_bytes_total{job=~\"$job\",container_name=~\"$container_name\"}[5m])",
     "legendFormat": " {{ container_name }}"
    }
   ]
  }
 ]
}