{
 "title": "Dex Metrics",
 "description": "0xERR0R / dex metrics exporter Dashboard",
 "tags": [
  "prometheus",
  "dex"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job_postfix", "label": "Jobs postfix", "query": "_dex" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "container", "label": "container", "query": { "query": "dex_container_running" } },
   { "name": "range", "query": "1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Container alive",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dex_container_running{container_name=~\"$container\", job=~\"$job.*\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Last $range CPU Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(dex_cpu_utilization_percent{container_name=~\"$container\", job=~\"$job.*\"}[$range])",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dex_container_running{container_name=~\"$container\", job=~\"$job.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Containers down",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dex_container_running{container_name=~\"$container\", job=~\"$job.*\"} == 0)"
    }
   ]
  },
  {
   "title": "Last $range Memory Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(dex_memory_usage_bytes{container_name=~\"$container\", job=~\"$job.*\"}[$range])",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU usage Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(dex_cpu_utilization_percent{container_name=~\"$container\", job=~\"$job.*\"  }[$range])",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "dex_memory_usage_bytes{container_name=~\"$container\", job=~\"$job.*\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Network read / write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(dex_network_rx_bytes_total{container_name=~\"$container\", job=~\"$job.*\"}[$range])",
     "legendFormat": "rx - {{container_name}}"
    },
    {
     "expr": "-rate(dex_network_tx_bytes_total{container_name=~\"$container\", job=~\"$job.*\"}[$range])",
     "legendFormat": "tx- {{container_name}}"
    }
   ]
  },
  {
   "title": "Storage read / write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(dex_block_io_read_bytes_total{container_name=~\"$container\", job=~\"$job.*\"}[$range])",
     "legendFormat": "read - {{container_name}}"
    },
    {
     "expr": "-rate(dex_block_io_write_bytes_total{container_name=~\"$container\", job=~\"$job.*\"}[$range])",
     "legendFormat": "write - {{container_name}}"
    }
   ]
  }
 ]
}